# ClaudeCodeUI - Enclii Service Specification
# Web-based UI for Claude Code with Janua SSO integration

apiVersion: enclii.dev/v1alpha
kind: Service
metadata:
  name: claudecodeui
  project: madfam-automation
spec:
  build:
    type: dockerfile
    dockerfile: Dockerfile
  runtime:
    port: 3001
    replicas: 1
    healthCheck: /health
  env:
    # Janua OAuth2 Configuration (SSO-only mode)
    - name: JANUA_URL
      value: "https://auth.madfam.io"
    - name: JANUA_CLIENT_ID
      value: "jnc_lSGMbQtCGdHSctd4mEQoaklLBCv7xXhe"
    - name: JANUA_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: claudecodeui-secrets
          key: janua-client-secret
    - name: JANUA_REDIRECT_URI
      value: "https://agents.madfam.io/auth/callback"
    - name: JANUA_ALLOWED_EMAILS
      value: "admin@madfam.io"  # Single-user SSO whitelist
    # JWT Configuration (matches Janua's 8-hour window)
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: claudecodeui-secrets
          key: jwt-secret
    - name: JWT_EXPIRATION
      value: "8h"
    # Application Settings
    - name: NODE_ENV
      value: "production"
    - name: CONTEXT_WINDOW
      value: "160000"
    # Auto-Claude Agent Integration
    - name: AGENT_API_URL
      value: "https://agents-api.madfam.io"
    - name: KUBERNETES_NAMESPACE
      value: "madfam-automation"
    - name: IN_CLUSTER
      value: "false"
